version: '2'
services:
    appname-app:
        image: appname
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://appname-mysql:3306/appname?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    appname-mysql:
        extends:
            file: mysql.yml
            service: appname-mysql
